name: CI (VLCKit)

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
    paths-ignore:
      - .gitignore
      - LICENSE
      - "**.md"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - "**.md"

env:
  VLC_HASH: 5e70837d8d766db6ca5052a2d4f503ad37243d9c # 3.0.16
  VLCKIT_HASH: 886e8a3b3412cc0163b08ef153ced18569246ca1 # 3.3.17

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run actionlint
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
  build:
    needs: [actionlint]

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: "videolan/VLCKit"
          ref: ${{ env.VLCKIT_HASH }}
      - uses: actions/checkout@v2
        with:
          repository: "videolan/vlc"
          path: libvlc/vlc
          ref: ${{ env.VLC_HASH }}
      - uses: actions/checkout@v2
        with:
          path: vlc-build
      - name: Prepare
        run: |
          cp vlc-build/patches/*.patch libvlc/patches/
          brew install gnutls
      - name: Build
        run: |
          ./compileAndBuildVLCKit.sh -x
      - name: Check
        run: ls -la
